off/urls.py
from django.conf.urls import url
from . import views

app_name = 'off'

urlpatterns = [

    url(r'^article/(?P<search>[\w\.\'\&%\s]+)/$', views.article, name='article'),
    url(r'^deconnexion/$', views.log_out, name='logout'),
    url(r'^inscription/$', views.login_registration, name='registration'),
    url(r'^compte/$', views.account, name='account'),
    url(r'^produit/(?P<product_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^mesproduits/$', views.my_products, name='my_products'),
    url(r'^mentions/$', views.mentions, name='mentions'),
]

pur_beurre/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from off import views
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'off/', include('off.urls', namespace='off'))
]

off/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=1000, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    user = models.ManyToManyField(User)
    category = models.ManyToManyField(Category)
    nutriscore = models.CharField(max_length=1)
    name = models.CharField(max_length=1000)
    url_image = models.CharField(max_length=1000, unique=True)
    url_link = models.CharField(max_length=1000, unique=True)

    def __str__(self):
        return self.name

off/forms.py
from django import forms


class OffForm(forms.Form):
    nom = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'size': '25', 'placeholder': 'Rechercher un produit'}))


class LoginForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", max_length=30)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)


class RegistrationForm(forms.Form):
    pseudo = forms.CharField(label="Nom d'utilisateur", max_length=30, required=True)
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput(), required=True)

off/views.py
import requests
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import OffForm, LoginForm, RegistrationForm
from .models import Category, Product
from .constants import *


def home(request):
    """ homepage, when the user performs a search, if the desired product is not in the database,
     use the openfoodfact API to find it and save it in the database """
    if request.method == 'POST':
        form = OffForm(request.POST)
        if form.is_valid():
            search_terms = form.cleaned_data['nom']
            mini_search_terms = search_terms.lower()
            first_maj_search_terms = search_terms.capitalize()
            if len(Product.objects.filter(name=mini_search_terms)) == 0:
                all_products = []
                for category in CATEGORIES_LIST:
                    api = 'https://fr.openfoodfacts.org/cgi/search.pl'
                    config = {
                        'action': 'process',
                        'search_terms': first_maj_search_terms,
                        'tagtype_0': 'categories',
                        'tag_contains_0': 'contains',
                        'tag_0': category,
                        'page_size': 1,
                        'json': 1
                    }
                    response = requests.get(api, params=config)
                    results = response.json()
                    recovered_product = results['products']
                    all_products.extend(recovered_product)

                good_product = []
                for product in all_products:
                    if 'product_name_fr' in product:
                        if product['product_name_fr'] == first_maj_search_terms and len(
                                clean_cat(product['categories'].split(","), CATEGORIES_LIST)) > 0:
                            good_product.append(product)
                selected_products = []

                if len(good_product) > 0:
                    if len(good_product) > 1:
                        good_product = [good_product[0]]

                    for product in good_product:
                        if valid_product(KEYS, product):
                            cat = clean_cat(product['categories'].split(","), CATEGORIES_LIST)
                            nutriscore = product['nutrition_grade_fr']
                            name = product['product_name_fr'].lower()
                            url_picture = product['image_url']
                            url_link = product['url']

                            key = [nutriscore, name, cat, url_picture, url_link]
                            selected_products.append(key)
                    if len(selected_products) > 0:
                        product_to_insert = selected_products[0]
                        element = Product.objects.create(name=product_to_insert[1].lower(), nutriscore=product_to_insert[0],
                                                         url_image=product_to_insert[3],
                                                         url_link=product_to_insert[4])

                        for cat in product_to_insert[2]:
                            element.category.add(Category.objects.get(name=cat))
                            element.save()

            return redirect('off:article', search=search_terms)

    else:
        form = OffForm()
    return render(request, 'off/home.html', locals())

# Access information account
@login_required(login_url='off:registration')  # redirect when user is not logged in
def account(request):
    user = User.objects.get(id=request.user.id)
    form = OffForm()
    return render(request, 'off/account.html', locals())


@login_required(login_url='off:registration')  # redirect when user is not logged in
def my_products(request):
    # Access to saved products
    user = User.objects.get(id=request.user.id)
    products = user.product_set.all().order_by('nutriscore')
    form = OffForm()
    paginate = True
    paginator = Paginator(products, 9)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products = paginator.page(paginator.num_pages)
    return render(request, 'off/myproducts.html', locals())


def article(request, search):
    # Returns products in the same category with a higher nutritional rating
    search = search.lower()
    researched_product = get_object_or_404(Product, name=search)
    nutriscore_researched_product = researched_product.nutriscore
    categories = Category.objects.filter(product__name=search).values_list('id', flat=True)
    products = Product.objects.filter(category__id__in=categories).filter(
        nutriscore__lt=nutriscore_researched_product).distinct().exclude(name=researched_product.name).order_by('nutriscore')

    paginate = True
    paginator = Paginator(products, 9)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products = paginator.page(paginator.num_pages)

    form = OffForm()

    # Product backup
    if request.method == 'POST':
        product = request.POST.get('id_product', False)
        user = User.objects.get(id=request.user.id)
        product_to_save = Product.objects.get(id=product)
        product_to_save.user.add(user)
        product_to_save.save()

    # Products saved by a user
    if request.user.is_authenticated:
        user = User.objects.get(id=request.user.id)
        memory = user.product_set.all()

    return render(request, 'off/articles.html', locals())


def login_registration(request):
    """ Display two forms, the first to register, the second to connect """
    login_error = False
    registration_error = False
    form = OffForm()
    if request.method == 'POST':
        login_form = LoginForm(request.POST)

        if login_form.is_valid():

            username = login_form.cleaned_data["username"]
            password = login_form.cleaned_data["password"]
            user = authenticate(username=username,
                                password=password)  # Check if data are correct
            if user:  # If the returned object is not None
                login(request, user)  # we connect user
                return redirect('home')
            else:  # otherwise an error is displayed
                login_error = True
                registration_form = RegistrationForm()

        else:
            registration_form = RegistrationForm(request.POST)
            if registration_form.is_valid():
                username = registration_form.cleaned_data["pseudo"]
                email = registration_form.cleaned_data["email"]
                password = registration_form.cleaned_data["password"]
                if User.objects.filter(email=email):
                    registration_error = True
                else:
                    user = User.objects.create_user(username, email, password)
                    login(request, user)
                    return redirect('home')

    else:
        login_form = LoginForm()
        registration_form = RegistrationForm()

    return render(request, 'off/login.html', locals())


def log_out(request):
    logout(request)
    return redirect('home')


def detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    product_nutriscore = product.nutriscore
    form = OffForm()
    nutriscores = ['a', 'b', 'c', 'd', 'e']
    return render(request, 'off/detail.html', locals())


def mentions(request):
    return render(request, 'off/mentions.html')


def valid_product(keys, all_products):
    """ Returns true if all the desired keys are in the dictionary  """

    for key in keys:
        if key not in all_products:
            return False
    return True


def clean_list(products_list):
    """ Removes white space in front of the name of each category  """
    for i, elt in enumerate(products_list):
        if elt[0] == " ":
            elt = elt[1:]
            products_list[i] = elt
    return products_list


def clean_cat(list_categories_product, list_categories):
    """ Returns a list which contains the categories present in the two lists placed in parameter  """
    final_list = []
    list_cat = clean_list(list_categories_product)
    for category in list_cat:
        if category in list_categories:
            final_list.append(category)
    return final_list

off/templates/off/account.html
{% extends 'off/home.html' %}
{% load static %}

{% block css %}
    <style type="text/css">
          header { height: 330px; padding-top: 7rem; background: black center url({% static 'off/img/remy-5.jpg' %}); }
          header .row { margin-top: 130px; }
          .produit { border: 1px solid white; background-color: rgb(248, 225, 193); font-size: 1.5em;}
          .email { font-size: 1.5em; }
          @media (min-width: 992px) {
            #mainNav { background-color: white; }
          }
          @media (max-width: 768px) {
              .email {
                font-size: 1em;
              }
            }
   </style>
{% endblock%}

{% block header %}
    <header class="text-center">
        <div class="container ">
            <div class="row justify-content-center  ">
                <div class="col-xs-8 produit" >
                    <p class="mb-0 font-weight-bold mr-4 ml-4"> {{ user.username|capfirst }}</p>
                </div>
            </div>
        </div>
    </header>

{% endblock %}
{% block content %}
<section class="page-section bg-primary " id="about">
    <div class="container-fluid">
        <div class="row d-flex justify-content-center">
          <div class="col-xs-8 border border-info email">
              <div class="ml-2 mr-2">{{ user.email }}</div>
          </div>
            </div>
    </div>
</section>
{% endblock %}

off/templates/off/articles.html
{% extends 'off/home.html' %}
{% block css %}
    <!-- Latest compiled and minified CSS -->

    <style type="text/css">
          .img-produit { width: 90%; height: 200px; position: relative; }
          .badge { background-color: green; position: absolute; left: 77%;  font-size: 1.8em; }
          header { height: 330px; padding-top: 7rem; background: black center url({{ researched_product.url_image }})}
          #no_product { font-size: 1.3em; }

          .produit { border: 1px solid white; background-color: rgb(248, 225, 193); font-size: 1.5em;}
          header .row { margin-top: 130px;}

          .pager { list-style-type: none; display: flex; justify-content: center; }
          @media (min-width: 992px) {
            #mainNav { background-color: white; }
            #mainNav .navbar-nav .nav-item .nav-link {
                color: black; }
            #mainNav .navbar-nav .nav-item .nav-link:hover {
                color: black;
  }
          }
    </style>
{% endblock %}

{% block header %}
    <header class="text-center">
        <div class="container ">
            <div class="row justify-content-center  ">
                <div class="col-md-3 produit" >
                    <p class="mb-0 font-weight-bold"> {{ researched_product.name|truncatewords:3|capfirst }}</p>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}

        <section class="page-section bg-primary " id="about">
            <div class="container-fluid">
              <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                  <h2 class="text-center ">Vous pouvez remplacer cet aliment par :</h2>
                  <hr class="divider bg-primary my-4">

                    {% if not products %}
                        <p id="no_product">Nous n'avons trouvé aucun produit avec une meilleur nutriscore que "{{  researched_product.name }}" !</p>

                    {% else %}
                       <div class="row">

                        {% for product in products %}
                        <div class="col-sm-4 col-xs-8 mb-4" >
                            <div>
                                <a href="{% url 'off:detail' product.id %}"><img src="{{ product.url_image }}" class="mt-2 mb-2 img-produit"></a>
                                <span class="badge badge-pill">{{ product.nutriscore|capfirst }}</span>
                                <p class="font-weight-bold">{{ product.name|capfirst }}</p>
                                {% if user.is_authenticated %}

                                    {% if product not in memory %}
                                        <form method="post" action="{% url 'off:article' search %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="id_product" value="{{ product.id }}" >
                                            <button type="submit">Sauvegarder</button>
                                        </form>
                                    {% endif %}

                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                     {% endif %}

                    </div>
                </div>
              </div>

                {% if paginate %}
                  <div class="row">
                      <div class="col-lg-12 text-center">
                          <nav aria-label="">
                            <ul class="pager">
                              {% if products.has_previous %}
                                  <li><a href="?page={{ products.previous_page_number }}">Précédent/</a></li>
                              {% endif %}
                              {% if products.has_next %}
                                  <li><a href="?page={{ products.next_page_number }}">Suivant</a></li>
                              {% endif %}
                            </ul>
                          </nav>
                      </div>
                  </div>
                {% endif %}
            </div>
        </section>

{% endblock %}

off/templates/off/detail.html
{% extends 'off/home.html' %}
{% block css %}
    <!-- Latest compiled and minified CSS -->

    <style type="text/css">
          .img-produit { width: 90%; height: 200px; position: relative; }
          .badge { background-color: green; position: absolute; left: 77%;  font-size: 1.8em; }
          header { height: 330px; padding-top: 7rem; background: black center url({{ product.url_image }})}
          #recherche { width: 140px; height: 200px; }
          .produit { border: 1px solid white; background-color: rgb(248, 225, 193); font-size: 1.5em;}
          header .row { margin-top: 130px; }
          #lien { font-size: 1.5em; }

          .liste_nutriscore { font-size: 2.5em; }

          .pager { list-style-type: none; display: flex; justify-content: center; }
          @media (min-width: 992px) {
            #mainNav { background-color: white; }
            #mainNav .navbar-nav .nav-item .nav-link {
                color: black; }
            #mainNav .navbar-nav .nav-item .nav-link:hover {
                color: black;
  }
          }
    </style>
{% endblock %}
{% block header %}
    <header class="text-center">
        <div class="container ">
            <div class="row justify-content-center ">
                <div class="col-md-4 produit" >
                    <p class="mb-0 font-weight-bold">{{ product.name|capfirst }}</p>
                </div>
            </div>
        </div>
    </header>
<hr class="divider light my-2">
{% endblock %}


{% block content %}
<section class="page-section bg-primary" id="about">
    <div class="container">
      <div class="row">
          <div class="col-sm-6">
              <div class="row">
                  <div class="col-sm-12 text-center"><h1>Nutriscore</h1></div>
                  <div class="col-sm-12 text-center ">
                      <ul class="list-unstyled d-flex justify-content-center">
                          {% for nutriscore in nutriscores %}
                            {% if nutriscore == product_nutriscore %}
                                <li class="mr-3 liste_nutriscore font-weight-bold">{{ nutriscore|capfirst }}</li>
                            {% else %}
                                <li class="mr-3 liste_nutriscore">{{ nutriscore|capfirst }}</li>
                            {% endif %}
                          {% endfor %}
                      </ul>
                  </div>
              </div>
          </div>

          <div class="col-sm-6  text-center"><h1>Repères pour 100g</h1></div>
      </div>
        <div class="row d-flex justify-content-center">
            <div class="col-sm-5 text-center mt-2" >
                <a href="{{ product.url_link }}" id="lien" class="text-decoration-none"><div class="border">Voir la fiche d'OpenFoodFacts</div></a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

off/templates/off/home.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Pur Beurre</title>

    {% load static %}
  <!-- Font Awesome Icons -->
  <link href="{% static 'off/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="{% static 'off/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'off/css/creative.css' %}" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">

  <style type="text/css">
          #valid { height : 34px; }
          section img { width : 100%; height : 200px; }
          .page-section { padding: 3rem 0; }
          nav .font-weight-bold { font-family: "Open Sans", sans-serif; font-size: 2em;}
          h1, h2, h3 { font-family: "Open Sans", sans-serif; }
          p.text-white { font-size : 1.2em; }
          body { font-family: "Scope One", sans-serif; }
          header input { height : 34px; }


          @media (max-width: 768px) {
              section img { height: 100px; width : 50%; }
              .img2 { margin-top: 15px;}
              header.masthead { padding-top: 8rem; }

              }
          @media (min-width: 992px) {
              header h2 { font-size: 2.2em;}
              .detail-nav { display: none;}

              }
          @media (max-width: 410px) {
              nav .font-weight-bold { font-size: 1.4em; }
              }

   </style>
  {% block css %}{% endblock %}
</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container-fluid">
      <a href="{% url 'home' %}"><img src="{% static 'off/img/logo.png' %}" alt="logo"></a>
      <h3 class="font-weight-bold ml-2">PUR BEURRE</h3>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
            <form class="form-row mt-4 mr-2" action="{% url 'home' %}" method="post">
              {% csrf_token %}
              {{ form.as_p }}
            </form>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link js-scroll-trigger" href="{% url 'off:account' %}"><img src="{% static 'off/img/compte.png' %}"><span class="detail-nav">Mes infos</span></a>
            {% else %}
            <a class="nav-link js-scroll-trigger" href="{% url 'off:registration' %}"><img src="{% static 'off/img/compte.png' %}"><span class="detail-nav">Se connecter</span></a>
            {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'off:my_products' %}"><img src="{% static 'off/img/carotte.png' %}"><span class="detail-nav">Mes Produits</span></a>
          </li>
          <li class="nav-item mt-2">
            {% if user.is_authenticated %}
            <a class="nav-link js-scroll-trigger" href="{% url 'off:logout' %}"><img src="{% static 'off/img/menu.png' %}"><span class="detail-nav">Déconnexion</span></a>
            {% else %}
            <a class="nav-link js-scroll-trigger" href="{% url 'home' %}"><img src="{% static 'off/img/menu.png' %}"><span class="detail-nav">Accueil</span></a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>



  <!-- Masthead -->
{% block header %}
  <header class="masthead">

    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 ">
          <h1 class="text-white font-weight-bold">Du gras, oui, mais de qualité !</h1>
        </div>
        <div class="col-lg-7 col-md-10 align-self">
          <h2 class="text-white font-weight-bold">Trouvez un produit de substitution pour ceux que vous consommez tous les jours</h2>
        </div>

        <div class="col-lg-12 align-self-baseline justify-content-center">
          <div class="row justify-content-center mt-3 ">
              <form class="form-row" action="{% url 'home' %}" method="post">
                <div class="input-group d-flex justify-content-around ">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button class="btn btn-primary" id="valid" type="submit">Envoyer</button>
                </div>
              </form>
          </div>
        </div>
      </div>
    </div>

  </header>


</div>
  {% endblock %}

  {% block content %}
  <hr class="divider light my-2">

  <!-- About Section -->
  <section class="page-section bg-primary" id="about">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="text-white mt-0">Colette et Rémi</h2>
          <hr class="divider light my-4">
          <p class="text-white mb-4">Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille.</p>
          <div class="row d-flex justify-content-center align-items-end">
            <div class="col-xs-2 col-sm-5 img1"><img src="{% static 'off/img/colette-5.jpg' %}"></div>
            <div class="col-xs-2 col-sm-5 img2 "><img src="{% static 'off/img/remy-4.jpg' %}"></div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <hr class="divider light my-1">

  <!-- Services Section -->

  <hr class="divider light my-1">

  <!-- Contact Section -->
  <section class="page-section" id="contact">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
            <h2 class="mt-0">Contactez-nous !</h2>
          <hr class="divider my-4">
          <p class="text-muted mb-5">Vous souhaitez rejoindre notre équipe où nous poser une question :</p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
          <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
          <div>+33 6.23.46.33.98</div>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
          <!-- Make sure to change the email address in anchor text AND the link below! -->
          <a class="d-block" href="mailto:mail@mail.com">mail@mail.com</a>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}

  <!-- Footer -->
  <footer class="bg-light py-5">
    <div class="container">
        <div class="row d-flex justify-content-around">
            <a href="{% url 'off:mentions' %}" class="text-decoration-none"><div class="col-xs-6  text-muted">Mentions Légales</div></a>
            <a href="/#contact" class="text-decoration-none"><div class="col-xs-6  text-muted">Contact</div></a>
        </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'off/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'off/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'off/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'off/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'off/js/creative.min.js' %}"></script>

</body>
</html>

off/templates/off/myproducts.html
{% extends 'off/home.html' %}
{% load static %}
{% block css %}
    <style type="text/css">

          header { height: 330px; padding-top: 7rem; background: black center url({% static 'off/img/remy-5.jpg' %}); }
          .produit { border: 1px solid white; background-color: rgb(248, 225, 193); font-size: 1.5em;}
          header .row { margin-top: 130px; }
          .img-produit { width: 90%; height: 200px; position: relative; }
          .badge { background-color: green; position: absolute; left: 77%;  font-size: 1.8em; }


          .pager { list-style-type: none; display: flex; justify-content: center; }
          @media (min-width: 992px) {
            #mainNav { background-color: white; }

          }
    </style>
{% endblock %}

{% block header %}
    <header class="text-center">
        <div class="container ">
            <div class="row justify-content-center  ">
                <div class="col-md-3 produit" >
                    <p class="mb-0 font-weight-bold"> {{ user.username|capfirst }}</p>
                </div>
            </div>
        </div>
    </header>
{% endblock %}


{% block content %}

        <section class="page-section bg-primary " id="about">
            <div class="container-fluid">
              <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                  <h2 class="text-center ">Voici vos produits sauvegardés :</h2>
                  <hr class="divider bg-primary my-4">
                    <div class="row">

                        {% for product in products %}
                        <div class="col-sm-4 col-xs-8 mb-4" >
                            <div>
                                <a href="{% url 'off:detail' product.id %}"><img src="{{ product.url_image }}" class="mt-2 mb-2 img-produit"></a>
                                <span class="badge badge-pill">{{ product.nutriscore|capfirst }}</span>
                                <p class="font-weight-bold">{{ product.name }}</p>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
              </div>

                {% if paginate %}
                  <div class="row">
                      <div class="col-lg-12 text-center">
                          <nav aria-label="">
                            <ul class="pager">
                              {% if products.has_previous %}
                                  <li><a href="?page={{ products.previous_page_number }}">Précédent/</a></li>
                              {% endif %}
                              {% if products.has_next %}
                                  <li><a href="?page={{ products.next_page_number }}">Suivant</a></li>
                              {% endif %}
                            </ul>
                          </nav>
                      </div>
                  </div>
                {% endif %}

            </div>
        </section>

{% endblock %}